notes/notes/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views
from authentication import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path(
        'admin/',
        admin.site.urls
    ),
    #authentication
    path(
        'login/',
        auth_views.LoginView.as_view(),
        name='login',
    ),
    path(
        'logout/',
        auth_views.LogoutView.as_view(),
        name='logout',
    ),
    path(
        'signup/',
        auth_views.UserCreate.as_view(),
        name='sign-up'
    ),
    #notes
    path(
        'notes/',
        views.NoteList.as_view(),
        name='note-list'

    ),
    path(
        'notes/<str:pk>/update',
        views.NoteUpdateView.as_view(),
        name='note-update'
    ),
    path(
        'notes/<str:pk>/delete',
        views.NoteDeleteView.as_view(),
        name='note-delete'
    ),
    path(
        'notes/create',
        views.NoteCreateView.as_view(),
        name='create'
    ),
    path(
        'notes/email',
        views.NotificationView.as_view(),
        name='email'
    ),
    #wedpush
    path(
        'send_push',
        views.send_push,
    ),
    path(
        'webpush/',
        include('webpush.urls')
    ),
    path(
        'web',
        views.webpush,
    ),
    path(
        'sw.js',
        TemplateView.as_view(template_name='sv.js', content_type='application/x-javascript')
    )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notes/authentication/models.py
from django.db import models

notes/board/models.py
from django import urls
from django.db import models
from django.conf import settings


class Note(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    created = models.DateField(auto_now=True)
    deadline = models.DateField(blank=True)
    user_notes = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='users_project',
        on_delete=models.CASCADE,
    )

    # def get_absolute_url(self):
    #     return urls.reverse('note-list', args=[str(self.id)])

    def __str__(self):
        return self.name

notes/authentication/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import models


class LoginForm(auth_forms.AuthenticationForm):
    username = auth_forms.UsernameField(
        label='username',
        widget=forms.TextInput(
            attrs={'autofocus': True}
        )
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={'autocomplete': 'current-password'}
        ),
    )


class CreateUserForm(auth_forms.UserCreationForm):
    class Meta:
        model = models.User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.save()
        return user

notes/board/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms
from django.contrib.auth import models


class ContactForm(forms.ModelForm):
    class Meta:
        model = models.User
        fields = [
            'username',
            'email'
        ]

notes/authentication/views.py
from time import sleepfrom urllib import requestfrom django.views import genericfrom django.contrib import messagesfrom django.shortcuts import renderfrom django import urlsfrom django.contrib.auth import viewsfrom django.shortcuts import redirectfrom django.contrib.messages.views import SuccessMessageMixinfrom authentication import formsclass LoginView(views.LoginView):    form_class = forms.LoginForm    template_name = 'login.html'    success_url = urls.reverse_lazy('note-list')    def dispatch(self, request, *args, **kwargs):        if request.user.is_authenticated:            return redirect('/notes/')        return super().dispatch(request, *args, **kwargs)class LogoutView(views.LogoutView):    next_page = urls.reverse_lazy('login')class UserCreate(generic.FormView):    form_class = forms.CreateUserForm    success_url = urls.reverse_lazy('login')    template_name = 'signup.html'    def form_valid(self, form):        form.save()        return super(UserCreate, self).form_valid(form)    def form_invalid(self, form):        return super(UserCreate, self).form_invalid(form)

notes/board/views.py
import json
from django import urls
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST
from webpush import send_user_notification
from django.contrib.auth import models as auth_model
from board import models, forms
from board.service import send
from .tasks import send_spam_email

class NoteList(LoginRequiredMixin, generic.ListView):
    model = models.Note
    template_name = 'products.html'

    def get_queryset(self):
        user = self.request.user
        return user.users_project.all()


class NoteCreateView(LoginRequiredMixin, generic.CreateView):
    model = models.Note
    fields = [
        'name',
        'description',
        'deadline',
        'user_notes'
    ]
    template_name = 'create.html'
    success_url = '/notes'


class NoteDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = models.Note
    template_name = 'delete.html'
    success_url = urls.reverse_lazy('note-list')


class NoteUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = models.Note
    fields = [
        'name',
        'description',
        'deadline',
    ]
    template_name = 'order_form.html'
    success_url = '/notes'


class NotificationView(generic.CreateView):
    form_class = forms.ContactForm
    template_name = 'email.html'
    success_url = '/notes'

    def form_valid(self, form):
        form.save()
        send_spam_email.delay(form.instance.email)
        return super().form_valid(form)

@require_GET
def webpush(request):
   webpush_settings = getattr(settings, 'WEBPUSH_SETTINGS', {})
   vapid_key = webpush_settings.get('VAPID_PUBLIC_KEY')
   user = request.user
   return render(request, 'webpush.html', {user: user, 'vapid_key': vapid_key})


@require_POST
@csrf_exempt
def send_push(request):
    try:
        body = request.body
        data = json.loads(body)

        if 'head' not in data or 'body' not in data or 'id' not in data:
            return JsonResponse(status=400, data={"message": "Invalid data format"})

        user_id = data['id']
        user = get_object_or_404(User, pk=user_id)
        payload = {'head': data['head'], 'body': data['body']}
        send_user_notification(user=user, payload=payload, ttl=1000)

        return JsonResponse(status=200, data={"message": "Web push successful"})
    except TypeError:
        return JsonResponse(status=500, data={"message": "An error occurred"})

notes/authentication/templates/login.html
{#<form action='.' method='post'>{% csrf_token %}#}
{#    {{ form.as_p}}#}
{#    <input type='submit' value='login'>#}
{#</form>#}
<!DOCTYPE html>
<html >

    <head>
        <title>Login</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


        <style>
            body,
            html {
                margin: 0;
                padding: 0;
                height: 100%;
                background: #7abecc !important;
            }
            .user_card {
                width: 350px;
                margin-top: auto;
                margin-bottom: auto;
                background: #74cfbf;
                position: relative;
                display: flex;
                justify-content: center;
                flex-direction: column;
                padding: 10px;
                box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
                border-radius: 5px;

            }

            .form_container {
                margin-top: 20px;
            }

            #form-title{
                color: #fff;

            }

            .login_btn {
                width: 100%;
                background: #33ccff !important;
                color: white !important;
            }
            .login_btn:focus {
                box-shadow: none !important;
                outline: 0px !important;
            }
            .login_container {
                padding: 0 2rem;
            }
            .input-group-text {
                background: #f7ba5b !important;
                color: white !important;
                border: 0 !important;
                border-radius: 0.25rem 0 0 0.25rem !important;
            }
            .input_user,
            .input_pass:focus {
                box-shadow: none !important;
                outline: 0px !important;
            }

            #messages{
                background-color: grey;
                color: #fff;
                padding: 10px;
                margin-top: 10px;
            }
        </style>

    </head>
    <body>
        <div class="container h-100">
            <div class="d-flex justify-content-center h-100">
                <div class="user_card">
                    <div class="d-flex justify-content-center">


                        <h3 id="form-title">LOGIN</h3>
                    </div>
                    <div class="d-flex justify-content-center form_container">
                        <form method="POST" action="">
                            <div class="input-group mb-3">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                <input type="text" name="username" placeholder="Username..." class="form-control">
                            </div>
                            <div class="input-group mb-2">
                                <div class="input-group-append">
                                    <span class="input-group-text"><i class="fas fa-key"></i></span>
                                </div>
                                    {% csrf_token %}
                                    <input type="password" name="password" placeholder="Password..." class="form-control" >
                            </div>

                                <div class="d-flex justify-content-center mt-3 login_container">
                                    <input class="btn login_btn" type="submit" value="Login">
                                </div>
                        </form>

                    </div>

                    <div class="mt-4">
                        <div class="d-flex justify-content-center links">
                            Don't have an account? <a href="{% url 'sign-up' %}" class="ml-2">Sign Up</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </body>

</html>

notes/authentication/templates/signup.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{ form.email }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1 }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2 }}
						</div>
                             {% if messages %}
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% endif %}
				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>

		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>
<form method="POST" action="">
    {% csrf_token %}
    {{ form.username.label }}
    {{ form.username }}

    {{ form.email.label }}
    {{ form.email }}

    {{ form.password1.label }}
    {{ form.password1 }}

    {{ form.password2.label }}
    {{ form.password2 }}
    <input type="Submit" name="Create user">
</form>

notes/board/templates/create.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}


<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<form action="" method="POST">
				{% csrf_token %}
				{{ form.management_form }}
				{% for field in form %}
					{{field}}
					<hr>
				{% endfor %}

				<input type="submit" name="Create">
			</form>

		</div>
	</div>
</div>


{% endblock %}

notes/board/templates/delete.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}

<br>
<div class="row">
	<div class="col-md-6">
		<div class="card card-body">


			<p>Are you sure you want to delete "{{item}}"?</p>

			<form action="{% url 'note-delete' note.id  %}" method="POST">
				
				{% csrf_token %}
				<a class="btn btn-warning" href="{% url 'note-list' %}">Cancel</a>

				<input class="btn btn-danger" type="submit" name="Delete">
			</form>
		</div>
	</div>
</div>

{% endblock %}

notes/board/templates/email.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}


<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<form action="" method="POST">
				{% csrf_token %}
				{{ form.as_p }}

				<input type="submit" name="Create">
			</form>

		</div>
	</div>
</div>


{% endblock %}

notes/board/templates/main.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>CRM</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        {%  include 'navbar.html' %}
            <div class="container-fluid">
            {% block content %}



            {% endblock %}
            </div>

    </body>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>

notes/board/templates/navbar.html
{% load static %}


<style>
  .hello-msg{
    font-size: 18px;
    color: #fff;
    margin-right: 20px;
  }
</style>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if request.user.is_staff %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'login' %}">Notes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'create' %}">Create note</a>
      </li>
       <li class="nav-item">
           <a class="nav-link" href="{% url 'email' %}">email</a>
      </li>
      {% endif %}
    </ul>
  </div>

  <span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'logout' %}">Logout</a></span>

</nav>

notes/board/templates/order_form.html
{%  extends 'main.html' %}
{% load static %}
{% block content %}


<div class="row">
	<div class="col-md-6">
		<div class="card card-body">

			<form action="" method="POST">
				{% csrf_token %}
				{{ form.management_form }}
				{% for field in form %}
					{{field}}
					<hr>
				{% endfor %}
				
				<input type="submit" name="Submit">
			</form>

		</div>
	</div>
</div>


{% endblock %}

notes/board/templates/products.html
{%  extends 'main.html' %}

{% block content %}

		<br>

		<div class="row">
			<div class="col-md">
				<div class="card card-body">
					<h5>Notes</h5>
				</div>
				<div class="card card-body">
					<table class="table">
						<tr>
							<th>Name</th>
							<th>description</th>
							<th>deadline</th>
                            <th>update</th>
                            <th>remove</th>
						</tr>

						{% for i in note_list %}
							<tr>
								<td>{{i.name}}</td>
								<td>{{i.description}}</td>
								<td>{{i.deadline}}</td>
                                <td><a class="btn btn-sm btn-info" href="{% url 'note-update' i.id %}">Update</a></td>
					            <td><a class="btn btn-sm btn-danger" href="{% url 'note-delete' i.id %}">Delete</a></td>
							</tr>
						{% endfor %}
						
					</table>
				</div>
			</div>
		</div>
{#        <div class="row">#}
{#            <div class="col-md">#}
{#				<div class="card card-body">#}
{#					<h5>Notification to email</h5>#}
{#                </div>#}
{#                    <div>#}
{#                        <form action='{% url "note-list" %}' method="post">#}
{#                            {% csrf_token %}#}
{#                            {{ form.as_p }}#}
{#                            <button type="submit">Send</button>#}
{#                        </form>#}
{#                    </div>#}
{#            </div>#}
{#        </div>#}
{% endblock content %}

notes/board/templates/webpush.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="vapid-key" content="{{ vapid_key }}">
    {% if user.id %}
        <meta name="user_id" content="{{ user.id }}">
    {% endif %}
    <title>Web Push</title>
    <link href="{% static '/css/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div>
        <form id="send-push__form">
            <h3 class="header">Send a push notification</h3>
            <p class="error"></p>
            <input type="text" name="head" placeholder="Header: Your favorite airline 😍">
            <textarea name="body" id="" cols="30" rows="10" placeholder="Body: Your flight has been cancelled 😱😱😱"></textarea>
            <button>Send Me</button>
        </form>
    </div>
    <script src="{% static '/js/registerSw.js' %}"></script>
    <script src="{% static '/js/site.js' %}"></script>
</body>
</html>